   version: '3'
   
   services:
     clair:
       image: quay.io/coreos/clair:v4.2.1
       ports:
         - "6060:6060"
       restart: always
       depends_on:
         - postgres

       volumes:
         - ./docker-compose-data/clair-config/:/config/:ro
         - ./docker-compose-data/clair-tmp/:/tmp/:rw

       command: 
         - -conf 
         - /config/config.yml
   
     postgres:
       image: postgres:12
       environment:
         - POSTGRES_USER=vboxuser
         - POSTGRES_PASSWORD=changeme
         - POSTGRES_DB=clair
       volumes:
         - /var/lib/postgresql/data
