---
log_level: debug-color
introspection_addr: ":8089"
http_listen_addr: ":6060"
updaters:
  sets:
    - ubuntu
auth:
  psk:
    key: 'c2VjcmV0'
    iss:
      - quay
      - clairctl
indexer:
  connstring: host=postgres user=vboxuser password=changeme dbname=clair sslmode=disable
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  indexer_addr: http://clair-indexer:6060/
  connstring: host=postgres user=vboxuser password=changeme dbname=clair sslmode=disable
  max_conn_pool: 100
  migrations: true
matchers: {}
notifier:
  indexer_addr: http://clair-indexer:6060/
  matcher_addr: http://clair-matcher:6060/
  connstring: host=postgres user=vboxuser password=changeme dbname=clair sslmode=disable
  migrations: true
  delivery_interval: 30s
  poll_interval: 1m
  webhook:
    target: "http://webhook-target/"
    callback: "http://clair-notifier:6060/notifier/api/v1/notification/"
